services:
  fastapi_service:
    image: backend_41811:latest
    container_name: fastapi_41811
    ports:
      - "43320:43320"
    environment:
      - TEXT2SQL_BACKEND_URL=http://text2sql_service:8000
    command: uvicorn main:app --host 0.0.0.0 --port 43320 --app-dir /app
    restart: always
    volumes:
      - ./Hainan_SQL-main:/app/Hainan_SQL-main
      - ./main.py:/app/main.py
      - ./db.sqlite3:/app/db.sqlite3

  text2sql_service:
    image: backend_41811:latest
    container_name: text2sql_41811
    ports:
      - "8000:8000"
    environment:
      - TEXT2SQL_MODEL_PATH=/app/Hainan_SQL-main/models
    command: python Hainan_SQL-main/text2sql_app/run.py
    restart: always
    volumes:
      - ./Hainan_SQL-main:/app/Hainan_SQL-main
