server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. 前端静态文件处理（支持Vue路由的history模式）
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. 转发FastAPI后端请求（关键：去掉location末尾的/）
    location /api {
        resolver 127.0.0.11 valid=30s;
        set $backend http://medical_fastapi:43320;
        proxy_pass $backend;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
    }
}